## Selection, Indexing and Broadcasting

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

 - **Indexing in 1D numpy array**

In [3]:
arr[5]

5

In [4]:
arr[:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- **Broadcasting**

Broadcasting a single value across a larger set of values

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5]=20

In [9]:
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10])

In [10]:
#slicing and setting to new variable acts as pointer to the original array
slice_of_arr = arr[0:6]

#use method copy() to avoid canges in original array

In [11]:
slice_of_arr

array([20, 20, 20, 20, 20,  5])

In [12]:
slice_of_arr[:] = 100

In [13]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [14]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

- **Indexing in 1D numpy arrays**

In [15]:
np.random.seed(20)
matrix = np.random.randint(1,10,(3,3))
matrix

array([[4, 5, 7],
       [8, 3, 1],
       [7, 9, 6]])

In [16]:
#dimension of matrix
matrix.shape

(3, 3)

In [17]:
#1st row
matrix[0,:]

array([4, 5, 7])

In [18]:
matrix[1,2]

1

In [19]:
matrix[0:2,1:3]

#for row range, 0 included, 2 excluded
#row 0 and row 1

#for col range, 1 included, 3 excluded

array([[5, 7],
       [3, 1]])

- **Conditional selection**

In [20]:
sample = np.arange(1,11)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#boolean array for elements greater than 4
bool_sample = sample > 4
bool_sample

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
#filtering out elements using bool_sample which are greater than 4
sample[bool_sample]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
#above three codes can be simply written as
sample[sample > 4]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
#TASK: check how many rolls were greater than 2

dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = len( dice_rolls[dice_rolls > 2] )

In [25]:
total_rolls_over_two

19