## **3 ways to generate numpy arrays:**

1. Transforming standard lists to numpy arrays
2. Built in functions
3. Generating random data

In [4]:
import numpy as np

### **1. Transforming standard lists to numpy array**

In [17]:
mylist = [1,2,3]   #standard list
type(mylist)

list

In [18]:
mylist

[1, 2, 3]

In [19]:
myarr = np.array(mylist)      #converted to a numpy array
type(myarr)

numpy.ndarray

In [21]:
myarr

array([1, 2, 3])

In [22]:
#2D example
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [23]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
np.array(matrix)     #transformed

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **2. Built in functions**   

In [27]:
#arange() in numpy is analogous to range() 
np.arange(0,10)
#0 included and 10 excluded

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
#use tuple as parameter to generate matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.eye(4)    #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#linspace() in numpy returns evenly spaced numbers over a specified interval
np.linspace(0,10,3)
#0 included, 10 included and 3 nos are returned

array([ 0.,  5., 10.])

In [40]:
np.linspace(0,10,3,endpoint=False)
#0 included, 10 excluded

array([0.        , 3.33333333, 6.66666667])

### **3. Generating random data**

In [41]:
#numpy contains its own full random library
np.random.rand(5)

#rand() creates an array with random samples from uniform dist
#i.e., rand(n) returns n uniformly distributed numbers 
#(i.e., between 0 and 1, 1 excluded)

array([0.8418405 , 0.39692212, 0.68880492, 0.62077635, 0.63910713])

In [49]:
np.random.rand(2,3)         #2x3 matrix

array([[0.68028996, 0.9182009 , 0.21488335],
       [0.55355919, 0.57574922, 0.41967697]])

In [51]:
np.random.rand(3,4,2)     #3 sets of 4x2 matrices

array([[[0.74073915, 0.21405177],
        [0.05480937, 0.93064824],
        [0.54191496, 0.88720311],
        [0.66365509, 0.08890056]],

       [[0.99616266, 0.69207895],
        [0.23232602, 0.67970025],
        [0.95308197, 0.48144039],
        [0.91732406, 0.77343273]],

       [[0.41814191, 0.04069823],
        [0.26823681, 0.77802018],
        [0.57809973, 0.77871768],
        [0.50848004, 0.94609721]]])

In [52]:
#random number from a standard normal distribution
#i.e., normal dist s.t. mean=0, var=1
np.random.randn(5)

array([ 0.60317472, -1.70119703, -0.3401252 ,  0.80639687,  0.82854781])

In [55]:
np.random.randn(4,3)

array([[ 0.45572738, -0.92261621,  0.69972518],
       [ 1.12492077, -1.63085334, -0.24201204],
       [ 0.05721266,  0.0742509 , -1.34334717],
       [-0.3206691 , -1.34958157,  1.06871593]])

In [57]:
#random integers
np.random.randint(0,20,5)
#5 random integers in interval [0,20)

array([12, 13,  1, 15,  9])

In [58]:
np.random.randint(0,20,(3,2))

array([[ 7,  2],
       [ 6,  6],
       [10, 15]])

In [62]:
#seeds are used to set a random state so that the randon results can be repoduced

np.random.seed(42)
np.random.rand(3)

#seed 42 corresponds to the fixed printed random values whre size can vary

array([0.37454012, 0.95071431, 0.73199394])

In [63]:
#letting the size be 5 for seed=42
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [64]:
#different seed value
np.random.seed(105)
np.random.rand(4)

array([0.08373992, 0.33350629, 0.85935575, 0.10568684])

In [66]:
np.random.seed(105)
np.random.randint(0,10,4)

array([0, 5, 6, 9])

## **Some numpy methods**

In [9]:
#numpy array to matrix (or any n dimensional shape) using reshape()

arr = np.arange(0,24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [73]:
arr.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [74]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
arr.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [5]:
#max(), min() are methods to find max, min values in an array

randarr = np.random.randint(0,50,5)
randarr

array([18, 49,  5, 11, 28])

In [6]:
randarr.max()

49

In [83]:
randarr.min()

1

In [7]:
#argmax() returns index of max value
#argmin() returns index of min value

print(randarr.argmax())
print(randarr.argmin())

1
2


In [16]:
#assignment operator does not copy elements, it points to the original elements in the numpy array

#copying an array in numpy
arr_copy = arr.copy()

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Some numpy attributes

In [87]:
#dtype is an attribute used to find data type of elements of a numpy array

randarr.dtype

dtype('int32')

In [89]:
#type() function returns structure/ data type of the variable randarr

type(randarr)

numpy.ndarray

In [92]:
#shape is an attribute that returns dimension of an array

a = arr.reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
a.shape

(6, 4)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [96]:
arr.shape

#output: (24,) denotes that arr is a 1D array with 24 elements

(24,)

### refer to __[numpy.org](https://numpy.org/)__  for more info and tutorials