## Numpy operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,6)
arr

array([0, 1, 2, 3, 4, 5])

- **Basic arithmetic operations**

In [3]:
#elemnt wise operation
arr + 5

array([ 5,  6,  7,  8,  9, 10])

In [4]:
#operations between arrays of same size
#element wise

arr + arr

array([ 0,  2,  4,  6,  8, 10])

In [5]:
arr * arr

array([ 0,  1,  4,  9, 16, 25])

In [6]:
#division in numpy results in a warning instead of an error
arr/arr

#0/0 yields nan (not a number)

C:\Users\Ritika Gupta\AppData\Local\Temp\ipykernel_17528\2854699682.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.])

In [7]:
1/arr

#1/0 yields infinity

C:\Users\Ritika Gupta\AppData\Local\Temp\ipykernel_17528\3257372542.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

In [8]:
#ZeroDivisionError without numpy
1/0

ZeroDivisionError: division by zero

- **Basic Mathematical functions**

In [9]:
#square root of every number in a numpy array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [10]:
#log of every element
np.log(arr)

C:\Users\Ritika Gupta\AppData\Local\Temp\ipykernel_17528\46260376.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [12]:
np.arctan(arr)

array([0.        , 0.78539816, 1.10714872, 1.24904577, 1.32581766,
       1.37340077])

In [13]:
arr-20

array([-20, -19, -18, -17, -16, -15])

In [14]:
np.abs(arr-20)

array([20, 19, 18, 17, 16, 15])

In [15]:
np.average(arr)

2.5

- **Summary statistics**

In [16]:
arr.sum()

15

In [17]:
arr.mean()

2.5

In [18]:
arr.max()

5

In [19]:
arr.min()

0

In [20]:
arr.var()

2.9166666666666665

In [21]:
arr.std()

1.707825127659933

- **2D array summary statistics and axis parameter**

In [22]:
#2D array summary statistics
matrix = np.arange(1,17).reshape(4,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
matrix.sum()

136

In [24]:
#sum of the elts of first row
matrix[0,:].sum()

10

In [25]:
#shorter way to find sum of all columns or all rows is by using the axis paramter

#axis=0 implies sum across the rows
#i.e., columnwise sum

#axis=1 implies sum across the columns
#i.e., rowwise sum

#columnwise sum (or, across the rows):
matrix.sum(axis=0)

array([28, 32, 36, 40])

In [26]:
#rowwise sum (or, across the columns):
matrix.sum(axis=1)

array([10, 26, 42, 58])

In [27]:
#TASK: check the total remaining in the account after the series of transactions

account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

print(account_transactions.sum())

2720
